# Use an official Node.js runtime as a parent image
FROM node:16

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY package*.json ./

# Install any needed packages
RUN npm install

COPY . .

# Make port 3100 available to the world outside this container
EXPOSE 3100

# Run the app when the container launches
CMD ["node", "server.js"]
