# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR /app

COPY package*.json ./

# Install any needed packages
RUN npm install

COPY . .

# Make port 3001 available to the world outside this container
EXPOSE 3001

# Run the command to start the server
CMD [ "node", "app.js" ]

